namespace ROQ.Data
{
    using ROQ.Data.Entities;
    using System;
    using System.Data.Entity;
    using System.Linq;

    public class ROQDBContext : DbContext
    {
        public DbSet<Users> Users{ get; set; }      
        public DbSet<LogAction> LogAction { get; set; }
        public DbSet<LogException> LogException { get; set; }

        //************* Following is example to add POCO class for database view : START *************
        //public virtual DbSet VWLOOKUPS { get; set; }

        public ROQDBContext()
            : base("name=ROQConnection")
        {
            //this.Configuration.LazyLoadingEnabled = false;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            //base.OnModelCreating(modelBuilder);
            //modelBuilder.HasDefaultSchema("SCOUTS");

            // to avoid autogenerated FK ScoutsUser_ID1
           // modelBuilder.Entity<ScoutsUser>()
           //.HasMany(e => e.ScoutsLeaders)
           //.WithOptional(e => e.ScoutsUser)
           //.HasForeignKey(e => e.ScoutsUser_ID);

           // modelBuilder.Entity<ScoutsUser>()
           //     .HasMany(e => e.ScoutsLeaders)
           //     .WithOptional(e => e.PendingUser)
           //     .HasForeignKey(e => e.PendingUserID);

           // // to avoid autogenerated FK ScoutsUser_ID1
           // modelBuilder.Entity<ScoutsUser>()
           //.HasMany(e => e.ScoutsParticipants)
           //.WithOptional(e => e.ScoutsUser)
           //.HasForeignKey(e => e.ScoutsUser_ID);

           // modelBuilder.Entity<ScoutsUser>()
           //     .HasMany(e => e.ScoutsParticipants)
           //     .WithOptional(e => e.PendingUser)
           //     .HasForeignKey(e => e.PendingUserID);

        }



        // Add a DbSet for each entity type that you want to include in your model. For more information 
        // on configuring and using a Code First model, see http://go.microsoft.com/fwlink/?LinkId=390109.

        // public virtual DbSet<MyEntity> MyEntities { get; set; }
    }

}