// <auto-generated />
namespace ROQ.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class NwTblLogActionLogExceptionUsers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NwTblLogActionLogExceptionUsers));
        
        string IMigrationMetadata.Id
        {
            get { return "201907032005594_NwTbl-LogAction-LogException-Users"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
